# obtained from this comment
# https://github.com/influxdata/telegraf/issues/6959#issuecomment-988931989
#-----------------------------------------------
apiVersion: v1
kind: ServiceAccount
metadata:
  name: telegraf-ds
  namespace: metrics
  labels:
    app.kubernetes.io/name: telegraf-ds

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: influx-stats-viewer
  labels:
    app.kubernetes.io/name: telegraf-ds
rules:
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes/proxy", "nodes/stats"]
    verbs: ["get", "list", "watch"]
---
#-----------------------------------------------
# 3. ClusterRoleBinding
#-----------------------------------------------
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: influx-telegraf-viewer
  labels:
    app.kubernetes.io/name: telegraf-ds
subjects:
  - kind: ServiceAccount
    name: telegraf-ds 
    namespace: metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: influx-stats-viewer

---
