apiVersion: v1
kind: Service
metadata:
  name: votingapp
  namespace: election
spec:
  ports:
  - port: 8008
    name: rest
  - port: 8800
    name: peer
  clusterIP: None
  selector:
    app.kubernetes.io/name: ledger-node
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: election
  name: ledger-node
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ledger-node
  serviceName: votingapp
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ledger-node
        app: ledger-node
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: "app.kubernetes.io/name"
                    operator: In
                    values:
                    - ledger-node
              topologyKey: "kubernetes.io/hostname"
      imagePullSecrets:
      - name: docker-registry
      containers:
      - image: hyperledger/sawtooth-settings-tp:chime
        imagePullPolicy: Always
        name: settings-tp
        command:
        - "bash"
        - -c
        - "settings-tp -vv -C tcp://$HOSTNAME:4004"
      - image: hyperledger/sawtooth-identity-tp:chime
        name: identity-tp
        command:
        - "bash"
        - -c
        - "identity-tp -vv -C tcp://$HOSTNAME:4004"
      - image: hyperledger/sawtooth-validator:chime
        name: validator
        ports:
        - containerPort: 4004
        - containerPort: 8800
        - containerPort: 5050
        env:
        - name: GENESIS_PATH
          value: "/mnt"
        command: [/bin/init-validator.sh]
        volumeMounts:
        - name: validator-key
          mountPath: "/etc/sawtooth/keys"
          readOnly: true
        - name: logs
          mountPath: "/var/logs/sawtooth"
        - name: genesis-batch
          mountPath: "/mnt"
          readOnly: true
      - image: hyperledger/sawtooth-pbft-engine:chime
        name: pbft-engine
        command:
        - bash
        - -c
        - "pbft-engine -vvv -C tcp://$HOSTNAME:5050"
      - image: hyperledger/sawtooth-rest-api:chime
        name: rest-api
        command:
        - bash
        - -c
        - "sawtooth-rest-api -v -C tcp://$HOSTNAME:4004 --bind 0.0.0.0:8008"
        ports:
        - containerPort: 8008
        volumeMounts:
        - name: logs
          mountPath: "/var/logs/sawtooth"
      - image: hyperledger/sawtooth-shell:chime
        name: shell
        command: ["bash"]
        args: ["-c", "sawtooth keygen && tail -f /dev/null"]
      - image: registry.gitlab.com/vidaloop/votingapp/package-registry/transaction-processor:v0.2.2
        name: election-management-tp
        command:
        - /bin/sh
        - -c
        - "VALIDATOR_HOST=$HOSTNAME /usr/local/bin/node /home/node/votingapp-ledger/dist/election-management-tp/index.js"
        env:
        - name: ROOT_CERT
          valueFrom:
            secretKeyRef:
              name: certificates
              key: system-root
              optional: false
        - name: SECDEV_CA_CERT
          valueFrom:
            secretKeyRef:
              name: certificates
              key: secdev-ca
              optional: false
        - name: AUTH_CERT
          valueFrom:
            secretKeyRef:
              name: certificates
              key: auth
              optional: false
      - image: registry.gitlab.com/vidaloop/votingapp/package-registry/transaction-processor:v0.2.2
        name: election-casting-tp
        command:
        - /bin/sh
        - -c
        - "VALIDATOR_HOST=$HOSTNAME /usr/local/bin/node /home/node/votingapp-ledger/dist/election-casting-tp/index.js"
      initContainers:
      - image: alpine:latest
        name: key-distribution
        command: [/bin/copy-keys.sh]
        volumeMounts:
        - name: validator-key
          mountPath: /mnt/node
        - name: validator-keys
          mountPath: /mnt/allkeys
      volumes:
      - name: validator-key
        emptyDir: {}
      - name: logs
        emptyDir: {}
      - name: validator-keys
        secret:
          secretName: validator-keys
          defaultMode: 0400
      - name: ems-keys
        secret:
          secretName: ems-keys
          defaultMode: 0400
      - name: genesis-batch
        configMap:
          name: genesis-batch

  volumeClaimTemplates:
  - metadata:
      name: ledger-data
      namespace: election
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "gp2"
      resources:
        requests:
          storage: 5Gi
---
